### ISSUE TITLE
Incorrect Content-Type results in firmware files opening in the browser

### ISSUE THREAD

**Issue by 0nelight** [openwrt/firmware-selector-openwrt-org#53] opened 2024-10-26 08:52 UTC
Download-Links to a notable amount of built Images via the Browser-Interface of the public [Firmware-Selector-Server](https://firmware-selector.openwrt.org/) on the [public ASU](https://sysupgrade.openwrt.org/) are being advertised as `content-type: text/stream; charset=utf-8` instead of from `content-type: application/octet-stream` the Webserver running on ASU.

This leads to the Issue where, when clicking on the Download-Button, instead of Firefox opening the Download-File-Dialog, it interprets the File as a Webpage and tries to render it. Workaround is clicking "Save Target as".

I am not sure if I should put this here or at ASU - therefore I created a [Ticket there too](https://github.com/openwrt/asu/issues/1059).

While Chrome Browser seems to take care of this misconfiguration, Firefox doesn't.

**Comment by mwarning** [comment] 2024-10-26 11:17
I cannot reproduce the problem. With Firefox 131.0.3 the generated images are downloaded as octet-stream.
![asu](https://github.com/user-attachments/assets/f11db023-129d-4f58-87d2-520bee2fca96)

**Comment by 0nelight** [comment] 2024-10-26 12:08
Hmm.. strange - for what device you produced your image? You applied a custom config? 

On my place here I tried with raspi3 device and set rootpw and ip and I get as mime in firefox and in chrome "text". Chrome then does some stuff to get this right anyway, Firefox takes "text" as "text". When I download with "save file as" the image works flawlessly.

**Comment by 0nelight** [comment] 2024-10-26 13:22
For "8devices Lima" you are right.. there the Type is correct octet-stream:
![grafik](https://github.com/user-attachments/assets/87f68a28-bd34-4e69-957e-e35eaf5620c9)

But for "Raspberry Pi 3B" it is not:
![grafik](https://github.com/user-attachments/assets/ae081978-2079-4850-9c8c-fe8ff0dd67e5)

I suspect the "gz" compression is the reason. Maybe related to [this Issue](https://github.com/openwrt/asu/issues/644)?

**Comment by AliveDevil** [comment] 2024-10-26 20:09
Context chain:
- Set up staticfiles: https://github.com/openwrt/asu/blob/main/asu/main.py#L39
- staticfiles from fastio is forwarded to starlette: https://github.com/fastapi/fastapi/blob/master/fastapi/staticfiles.py
- starlette returns FileResponse: https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L178
- Which, if MediaType is None (which it possibly always is), guesses the content type: https://github.com/encode/starlette/blob/master/starlette/responses.py#L301-L302
- Which is a bundled component: https://docs.python.org/3/library/mimetypes.html

All that is to say: ASU should probably register `mimetypes.add("application/octet-stream", ".img.gz")`.

**Comment by mwarning** [comment] 2024-10-28 18:57
Thank you for figuring this out. Let me close this ticket and hope this will get fixed on the ASU side.

**Closed by mwarning** 2024-10-28 18:57 UTC
